### ISSUE TITLE
Template folder spelling is incorrect for flask render_template.

### ISSUE THREAD

**Issue by surajkr1** [nikita9604/Blogging-Website-using-Flask#1]
In python template folder correct spelling is `templates` to render web pages in python.
Just a small spelling mistake.
Pointed for correction.
By the way,Project is nice and written in well manner.

Hope my issue will help u.
Thanks

**Comment by nikita9604** [comment]
Thank you so much for bringing this to my attention! I truly appreciate your keen eye for detail. The correction has been duly noted and addressed.

I am delighted to hear that you find the project nice and well-written. If you have any further suggestions or notice anything else that could be improved, please don't hesitate to let me know.

Once again, thank you for your help and support!
